# Generated by Django 4.1.7 on 2023-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_meal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
