# Generated by Django 4.1.7 on 2023-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
