# Generated by Django 4.1.7 on 2023-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_meal_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='bolaklar_soni',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='meal',
            name='ogirlik',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='sostav',
            field=models.TextField(default="tuz, yog', un"),
        ),
    ]
